### ISSUE TITLE
Set IPMITool to 1.8.14

### ISSUE THREAD

**Issue by niedbalski** [niedbalski/mr-provisioner-role#1]
infra-automation/ansible/roles/mr-provisioner/tasks/main.yml:8:
ipmitool needs to be a specific version for it to work with the
moonshot. From a historic conversation some details:

hrw : 6dec83ff5d28a4d492e6667802136436c4466cc8 is the first bad commit
hrw :     ID:369 - Fix lanplus interface bridging and response matching
any ipmitool version after 1.8.14 may or may not work, i.e. 1.8.18 was
failing for us

**Comment by gemagomez** [comment]
This is only the case for set ups that need to use moonshot.

**Comment by BaptisteGerondeau** [comment]
IPMI tool 1.8.14 is not available in the Debian repos... Meaning that pinning the version (i.e. ipmitool=1.8.14) would not work on a Debian install.
Ubuntu Trusty has 1.8.13 and Xenial 1.8.16. Debian (stretch) is at 1.8.18.

So installing the correct version by hand and passing the install path is the best way to tackle this issue at the moment.
